### PR TITLE
Fixed affilitation and added fig for citation counts

### PR DESCRIPTION
**Pull request by rajarshi**
It'd be useful if we could also include per-year citation counts for the first CDK paper.

Alternatively, are there other good ways to show growth in usage of the CDK over the years?

### CODE REVIEW

**Comment by egonw** [comment]
Sounds good to me to add these numbers. We should give the numbers for both articles, and be clear what source we have for the counts.

**Comment by rajarshi** [comment]
Yes - these are from Google. I'll add in some text and insert the figure. But I was unable to get citation counts for the first CDK paper from Google

**Comment by egonw** [comment]
This is what WoS gives:

image

The sums are lower than in the system, which seems to indicate they count citations from more entities than they actually have in the system.

**Comment by egonw** [comment]
See this Gist: https://gist.github.com/egonw/644ac7fb50c0d497af2e26a7a85f1105

**Comment by egonw** [comment]
OK, I now also added a second file with the total citation numbers in WoS, which are about 10% higher. But not all of these citing articles have records themselves, so that the other numbers are lower.

**Comment by egonw** [comment]
That aside, even the 395 is only in their core data set, and the unique number of citing documents is actaully 402 (for CDK I):

image

**Comment by egonw** [comment]
Here are the GScholar numbers for CDK I:

https://scholar.google.nl/citations?view_op=view_citation&hl=en&user=u8SjMZ0AAAAJ&citation_for_view=u8SjMZ0AAAAJ:u5HHmVD_uO8C

image

**Pull request merged**
