### PR TITLE
Benchmark

### PR DESCRIPTION
**Pull request by johnmay**
Still need to find time to write the section wording but run on 1.4.19 completed. Realised I was grabbing the "wrong" time from unix time.

### CODE REVIEW

**Comment by egonw** [comment]
@johnmay it reports merge conflicts... can you please check that?

**Comment by johnmay** [comment]
Hmm odd, sure will do

**Comment by johnmay** [comment]
Okay all done - barring any changes to wording etc. We need should zip up the benchmark folder and include it with the submission.

**Comment by rajarshi** [comment]
Looks good to me

**Pull request merged**
